FROM python:3.7-slim-bullseye

RUN mkdir -p /app
COPY requirements-celery.txt /app
COPY flaskapp/[^flaskapp] /app
WORKDIR /app
RUN apt update; apt install -y vim procps
RUN python3 -m pip install wheel; python3 -m pip install --upgrade pip; python3 -m pip install -r /app/requirements-celery.txt
ENTRYPOINT ["celery","-Atasks.app","worker","--loglevel=INFO"]
