version: "2"
services:
  mongo:
    image: mongo:4.2
    ports:
    - "27017:27017"
  redis:
    image: redis
    ports:
    - "6379:6379"
  rabbitmq:
    image: rabbitmq:management
    ports:
    - "5672:5672"
    - "15672:15672"
  web:
    image: "flaskapp:latest"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:5000"
  celery:
    image: "celeryapp"
    build:
      context: .
      dockerfile: Dockerfile.celery
