version: "2"
services:
  web:
    image: "flaskapp:latest"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:5000"
  celery:
    image: "celeryapp"
    build:
      context: .
      dockerfile: Dockerfile.celery
